version: '3.8'

services:
  knowledge-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-qa-system
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
      # Mount examples for testing
      - ./examples:/app/examples:ro
    environment:
      - PYTHONPATH=/app
      - KNOWLEDGE_DATA_DIR=/app/data
      - KNOWLEDGE_LOG_DIR=/app/logs
    networks:
      - knowledge-network
    depends_on:
      - ollama
      - chromadb
    restart: unless-stopped

  # Ollama service for LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - knowledge-network
    restart: unless-stopped
    # Pull Qwen model on startup
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull qwen:1.7b && 
             wait"

  # ChromaDB service for vector storage
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-service
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - knowledge-network
    restart: unless-stopped

networks:
  knowledge-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  chromadb_data:
    driver: local